### PR TITLE
appveyor-ci: windows ci test

### PR DESCRIPTION
**Pull request by quiltdata**

### CODE REVIEW

**Comment by mhassan102** [comment]
Software fails on windows:

- python 2.7 => pyarrow error
- python 3.5 => pytest registry fails
- python 3.4 => pyarrow error

https://ci.appveyor.com/project/quiltdata/quilt-compiler

**Comment by dimaryaz** [comment]
@mhassan102: pyarrow only has Win32 builds for Python 3.5 and 3.6 (see [here](https://pypi.python.org/pypi/pyarrow)) - so no point even trying other versions.

How do I see the pytest errors from 3.5?

**Comment by mhassan102** [comment]
@dimaryaz : Here you can find build logs :
https://ci.appveyor.com/project/quiltdata/quilt-compiler/build/1.0.1

**Comment by dimaryaz** [comment]
Ah, it's trying to run the registry unittests. We definitely don't need to support those on Windows. All you need is to run `pytest compiler` (or run `pytest` from the `compiler` directory); looks like all of those already pass.

**Comment by mhassan102** [comment]
Yeah, compiler test are pass.

So let me set TEST_REGISTRY: False to avoid this on windows
https://github.com/quiltdata/quilt-compiler/blob/appveyor-ci/appveyor.yml#L20

**Comment by mhassan102** [comment]
Without pytest registry we are ok with 3.5 on windows.

https://ci.appveyor.com/project/quiltdata/quilt-compiler/build/1.0.22

**Comment by asah** [comment]
Pls update appveyor.yml so it passes!

**Comment by akarve** [comment]
@mhassan102 Are you able to add Python 3.6 to the matrix?

**Comment by mhassan102** [comment]
@akarve Build is successful with 3.6 also.

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"
      TEST_REGISTRY: false

I had check it with my forked repo:
https://ci.appveyor.com/project/mhassan102/quilt-compiler/build/1.0.9

I didn't have access to quiltdata account now.

**Comment by quiltdata** [comment]
Yes please use forked repo, it was an accident that we have you main github
permissions! :-). Just issue pull requests and we'll merge!

**Pull request merged**
